# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\DenaCharts\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\BarChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\ColumnChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\LineChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\DataTableFromArray:
    public: true
  CPSIT\DenaCharts\DataProcessing\FileReaderCSV:
    public: true
