# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $currentLanguage: '@currentLanguage'

  CPSIT\DenaCharts\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  currentLanguage:
     class: TYPO3\CMS\Core\Site\Entity\SiteLanguage
     factory: '@CPSIT\DenaCharts\Language\CurrentSiteLanguageFactory'

  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\BarChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\ColumnChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\LineChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\ChartJsProcessor\PieChartProcessor:
    public: true
  CPSIT\DenaCharts\DataProcessing\DataTableFromArray:
    public: true
  CPSIT\DenaCharts\DataProcessing\FileReaderCSV:
    public: true

  CPSIT\DenaCharts\Form\ColorSchemeSelectorItemProvider:
    public: true
